packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ^5.7.3
  zod: ^3.23.8
  dayjs: ^1.11.13
  superjson: ^2.2.1
  "@t3-oss/env-nextjs": ^0.10.1
  tailwindcss: ^4.0.0
  postcss: ^8.4.5
  resend: ^4.1.2
  "@supabase/supabase-js": ^2.49.0
  "@supabase/ssr": ^0.6.1

catalogs:
  node:
    node: ^20.11.0
    "@types/node": ^20.11.0
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.0
  drizzle:
    drizzle-orm: ^0.41.0
    drizzle-zod: ^0.7.0
    drizzle-kit: ^0.30.5
    drizzle-seed: ^0.3.1
  trpc:
    "@trpc/client": ^11.0.0
    "@trpc/react-query": ^11.0.0
    "@trpc/server": ^11.0.0
  next15:
    next: 15.3.0
    "@types/next": ^15.3.0